### ISSUE TITLE
two way sync appears to have broken

### ISSUE THREAD

**Issue by mohammadaboalnadar** [argon-rbx/argon-legacy#2]
Regular vscode to roblox sync is working fine as far as I'm concerned but roblox to vscode sync is no longer working. Yes, the option is on

not sure what info I'm expected to provide but I'll be happy to provide any that I'm asked

**Comment by DervexDev** [comment]
Moved to [argon-legacy](https://github.com/argon-rbx/argon-legacy) as this the repo of the Argon version you are referring to.

I'm currently working on the [new version of Argon](https://github.com/argon-rbx/argon) and unfortunately I don't have time to fix issues present in this the old (legacy) version. Sorry for the inconvenience but I'm afraid you have to wait until the new version is ready.
