### ISSUE TITLE
Support for JetBrains Fleet

### ISSUE THREAD

**Issue by Naymmmm** [argon-rbx/argon-legacy#4]
Currently, I'm switching from VS Code to JetBrains Fleet.
Title literally says it all.

**Comment by DervexDev** [comment]
Moved to `argon-legacy` as this the version you are referring to.

Argon 2 is standalone executable so you will be able to use it with any editor once it is released. I won't be creating a plugin for JetBrains Fleet as it is quite a niche editor, however I am open to your contributions.
